language: java
jdk: oraclejdk8
sudo: false

before_install: chmod +x gradlew
install:
  - ""
script:
  - ./gradlew --continue check javadoc jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - find ~/.gradle/ -name *.lock -print0 | xargs -0 rm -f

cache:
  directories:
  - ~/.gradle

notifications:
  irc:
    channels:
      - "irc.esper.net#NovaAPI"
    on_success: change
    on_failure: always
    skip_join: true
  email: false
